version: '3.2'
services:
  sonarqube:
    build:
      context: sonarqube/
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /tmp/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube
  Gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://localhost'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '422:422'
    container_name: Gitlab
 #   volumes:
 #     - '$GITLAB_HOME/config:/etc/gitlab'
 #     - '$GITLAB_HOME/logs:/var/log/gitlab'
 #     - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
  #gerrit:
  #  image: gerritcodereview/gerrit
  #  ports:
  #    - "29418:29418"
  #    - "8081:8080"
    depends_on:
      - ldap
   # environment:
   #   - CANONICAL_WEB_URL=http://localhost:8081/
    # command: init
  ldap:
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    container_name: ldap
    environment:
      - LDAP_ADMIN_PASSWORD=secret
  ldap-admin:
    image: osixia/phpldapadmin
    ports:
      - "6443:443"
    container_name: ldap-admin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
